//
// Created by atsocs on 22/04/2020.
//

#ifndef CONSTANTS_3BB41D66AF15491BAB3076FA192ECAF3_H
#define CONSTANTS_3BB41D66AF15491BAB3076FA192ECAF3_H

#include "raylib.h"

#define SNAKKE_DEBUG
//#define SNAKKE_DEBUG_ALL

#define TARGET_FPS 60
#define BORDER_IN_PIXELS 10
#define BORDER_COLOR RED
#define SNAKE_COLOR GREEN
#define FRUIT_COLOR BLUE
#define CELL_WIDTH_IN_PIXELS 32
#define CELL_HEIGHT_IN_PIXELS 32
#define CELL_PADDING_WIDTH_IN_PIXELS (CELL_WIDTH_IN_PIXELS / 20)
#define CELL_PADDING_HEIGHT_IN_PIXELS (CELL_HEIGHT_IN_PIXELS / 20)
#define FRUIT_PADDING_WIDTH_IN_PIXELS (CELL_WIDTH_IN_PIXELS / 6)
#define FRUIT_PADDING_HEIGHT_IN_PIXELS (CELL_HEIGHT_IN_PIXELS / 6)
#define FRUIT_RADIUS_H ((((double)CELL_WIDTH_IN_PIXELS) / 2.0) - ((double)FRUIT_PADDING_WIDTH_IN_PIXELS))
#define FRUIT_RADIUS_V ((((double)CELL_HEIGHT_IN_PIXELS) / 2.0) - ((double)FRUIT_PADDING_HEIGHT_IN_PIXELS))
#define BOARD_SIZE 15
#define SCREEN_WIDTH_IN_CELLS BOARD_SIZE
#define SCREEN_HEIGHT_IN_CELLS BOARD_SIZE
#define SCREEN_WIDTH (2 * BORDER_IN_PIXELS + SCREEN_WIDTH_IN_CELLS * CELL_WIDTH_IN_PIXELS)
#define SCREEN_HEIGHT (2 * BORDER_IN_PIXELS + SCREEN_HEIGHT_IN_CELLS * CELL_HEIGHT_IN_PIXELS)
#define SNAKE_INITIAL_SIZE 1
#define SNAKE_INITIAL_SPEED 3.0
#define DIMENSION 2
#define HEALTH_MAX 100
#define FRUIT_BASE_SCORE 1
#define FRUIT_BASE_HEALTH_BENEFIT 5
#endif //CONSTANTS_3BB41D66AF15491BAB3076FA192ECAF3_H
